# Generated by Django 3.2.9 on 2022-07-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=9999, verbose_name='Adresa')),
                ('post_num', models.CharField(max_length=100, verbose_name='PSC')),
                ('country', models.CharField(max_length=9999, verbose_name='Krajina')),
                ('name', models.CharField(max_length=9999, verbose_name='Meno')),
                ('surname', models.CharField(max_length=9999, verbose_name='Priezvisko')),
                ('tel_number', models.IntegerField(verbose_name='Telefonne cislo')),
                ('dic', models.CharField(max_length=9999, verbose_name='DIC')),
                ('email', models.CharField(max_length=9999, verbose_name='Email')),
                ('date_of_order', models.DateTimeField(auto_now_add=True)),
                ('mark_as_completed', models.BooleanField(default=False)),
                ('order_id', models.CharField(max_length=9999, null=True)),
                ('transaction_id', models.CharField(max_length=9999, null=True)),
            ],
        ),
    ]
